services:
  rabbitmq:
    image: "rabbitmq:3.12.10-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./docker-conf/rabbitmq/data/:/var/lib/rabbitmq/

  connector_db:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=data
    volumes:
      - ./docker-conf/postgres/data/:/var/lib/postgresql/data/

  client_db:
    image: postgres:15.1-alpine
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=data
    volumes:
      - ./docker-conf/postgres2/data/:/var/lib/postgresql/data/

  adminer:
    image: adminer
    ports:
      - 8080:8080